<#assign title="请求详情 - 账单" />
<#include "layout/header.ftl"/>
            <div class="main   ">
        
        <div class="wrapper">
            <h1 class="bill-detail-title">请求详情</span></h1>
            <h3 class="bill-detail-app">懂球帝</h3>
                <table class="table-bill-detail">
                    <tr class="table-hd">
                        <th>日期</th>
                        <th>请求数</th>
                    </tr>
                <tr>
                        <td>2017-11-09</td>
                        <td>4.78w</td>
                    </tr><tr>
                        <td>2017-11-08</td>
                        <td>5.53w</td>
                    </tr><tr>
                        <td>2017-11-07</td>
                        <td>6w</td>
                    </tr><tr>
                        <td>2017-11-06</td>
                        <td>7.97w</td>
                    </tr><tr>
                        <td>2017-11-05</td>
                        <td>12.07w</td>
                    </tr><tr>
                        <td>2017-11-04</td>
                        <td>14.96w</td>
                    </tr><tr>
                        <td>2017-11-03</td>
                        <td>20.49w</td>
                    </tr><tr>
                        <td>2017-11-02</td>
                        <td>35.57w</td>
                    </tr><tr>
                        <td>2017-11-01</td>
                        <td>35.37w</td>
                    </tr><tr>
                        <td>2017-10-31</td>
                        <td>33.5w</td>
                    </tr><tr>
                        <td>2017-10-30</td>
                        <td>35.87w</td>
                    </tr><tr>
                        <td>2017-10-29</td>
                        <td>46.63w</td>
                    </tr><tr>
                        <td>2017-10-28</td>
                        <td>45.31w</td>
                    </tr><tr>
                        <td>2017-10-27</td>
                        <td>35.59w</td>
                    </tr><tr>
                        <td>2017-10-26</td>
                        <td>86</td>
                    </tr><tr>
                        <td>2017-10-25</td>
                        <td>45</td>
                    </tr><tr>
                        <td>2017-10-20</td>
                        <td>7</td>
                    </tr><tr>
                        <td>2017-06-11</td>
                        <td>2</td>
                    </tr><tr>
                        <td>2017-05-12</td>
                        <td>4</td>
                    </tr><tr>
                        <td>2017-05-11</td>
                        <td>12</td>
                    </tr><tr>
                        <td>2017-05-10</td>
                        <td>4</td>
                    </tr><tr>
                        <td>2017-04-24</td>
                        <td>1</td>
                    </tr><tr>
                        <td>2017-04-23</td>
                        <td>1</td>
                    </tr><tr>
                        <td>2017-04-21</td>
                        <td>1</td>
                    </tr><tr>
                        <td>2017-04-20</td>
                        <td>1</td>
                    </tr><tr>
                        <td>2017-04-19</td>
                        <td>6</td>
                    </tr><tr>
                        <td>2017-04-16</td>
                        <td>2</td>
                    </tr><tr>
                        <td>2017-04-14</td>
                        <td>4</td>
                    </tr><tr>
                        <td>2017-04-12</td>
                        <td>1</td>
                    </tr><tr>
                        <td>2017-04-11</td>
                        <td>57</td>
                    </tr><tr>
                        <td>2017-04-10</td>
                        <td>39</td>
                    </tr><tr>
                        <td>2017-04-09</td>
                        <td>19</td>
                    </tr><tr>
                        <td>2017-04-08</td>
                        <td>53</td>
                    </tr><tr>
                        <td>2017-04-06</td>
                        <td>4</td>
                    </tr><tr>
                        <td>2017-04-05</td>
                        <td>9</td>
                    </tr><tr>
                        <td>2017-04-03</td>
                        <td>4</td>
                    </tr><tr>
                        <td>2017-04-02</td>
                        <td>6</td>
                    </tr><tr>
                        <td>2017-04-01</td>
                        <td>21</td>
                    </tr><tr>
                        <td>2017-03-31</td>
                        <td>8</td>
                    </tr><tr>
                        <td>2017-03-30</td>
                        <td>22</td>
                    </tr><tr>
                        <td>2017-03-29</td>
                        <td>15</td>
                    </tr><tr>
                        <td>2017-03-28</td>
                        <td>9</td>
                    </tr><tr>
                        <td>2017-03-27</td>
                        <td>29</td>
                    </tr><tr>
                        <td>2017-03-24</td>
                        <td>1</td>
                    </tr><tr>
                        <td>2017-03-23</td>
                        <td>5</td>
                    </tr><tr>
                        <td>2017-03-22</td>
                        <td>2</td>
                    </tr><tr>
                        <td>2017-03-21</td>
                        <td>9</td>
                    </tr><tr>
                        <td>2017-03-20</td>
                        <td>22</td>
                    </tr><tr>
                        <td>2017-03-19</td>
                        <td>2</td>
                    </tr><tr>
                        <td>2017-03-18</td>
                        <td>24</td>
                    </tr><tr>
                        <td>2017-03-17</td>
                        <td>29</td>
                    </tr><tr>
                        <td>2017-03-16</td>
                        <td>24</td>
                    </tr><tr>
                        <td>2017-03-15</td>
                        <td>39</td>
                    </tr><tr>
                        <td>2017-03-14</td>
                        <td>35</td>
                    </tr><tr>
                        <td>2017-03-13</td>
                        <td>17</td>
                    </tr><tr>
                        <td>2017-03-12</td>
                        <td>11</td>
                    </tr><tr>
                        <td>2017-03-11</td>
                        <td>12</td>
                    </tr><tr>
                        <td>2017-03-10</td>
                        <td>62</td>
                    </tr><tr>
                        <td>2017-03-09</td>
                        <td>509</td>
                    </tr><tr>
                        <td>2017-03-08</td>
                        <td>188</td>
                    </tr><tr>
                        <td>2017-03-07</td>
                        <td>220</td>
                    </tr><tr>
                        <td>2017-03-06</td>
                        <td>93</td>
                    </tr><tr>
                        <td>2017-03-05</td>
                        <td>33</td>
                    </tr><tr>
                        <td>2017-03-04</td>
                        <td>9</td>
                    </tr><tr>
                        <td>2017-03-03</td>
                        <td>135</td>
                    </tr><tr>
                        <td>2017-03-02</td>
                        <td>109</td>
                    </tr><tr>
                        <td>2017-03-01</td>
                        <td>88</td>
                    </tr><tr>
                        <td>2017-02-28</td>
                        <td>161</td>
                    </tr><tr>
                        <td>2017-02-27</td>
                        <td>47</td>
                    </tr><tr>
                        <td>2017-02-26</td>
                        <td>1</td>
                    </tr><tr>
                        <td>2017-02-24</td>
                        <td>29</td>
                    </tr><tr>
                        <td>2017-02-23</td>
                        <td>6</td>
                    </tr><tr>
                        <td>2017-02-22</td>
                        <td>38</td>
                    </tr><tr>
                        <td>2017-02-21</td>
                        <td>237</td>
                    </tr><tr>
                        <td>2017-02-20</td>
                        <td>66</td>
                    </tr><tr>
                        <td>2017-02-19</td>
                        <td>12</td>
                    </tr><tr>
                        <td>2017-02-18</td>
                        <td>94</td>
                    </tr><tr>
                        <td>2017-02-17</td>
                        <td>49</td>
                    </tr>        </table> 
                </div>
        <div class="clear"></div>
        <div id="fill"></div>
        </div>
        <div class="ft">
          <span class="copyright">
                TinkerPatch.com     © 2017 </span>
          <span class="links">
                  <a href="https://github.com/tinkerPatch">Github开源</a> | <a href="/Docs/contract">用户协议</a> |<a href="mailto:admin@tinkerpatch.com">联系我们</a></span>  </span>
        </div>
        
        <script type="text/javascript">
        
          $('[data-toggle="tooltip"]').tooltip()
        
            var fillPadding = function() {
                $('#fill').height($('#fill').height() + window.innerHeight - ($('.main').offset().top + $('.main').height() + $('.ft').height()))
            }
            $(window).resize(fillPadding);
            fillPadding();
            $('.ft').show();
        </script>

<#include "layout/footer.ftl"/>